[package]
name = "bevy_scene_context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.13.0"
bevy_core = "0.13.0"
bevy_app = "0.13.0"
bevy_hierarchy = "0.13.0"
bevy_scene = "0.13.0"
